USE SCHEMA {{ SF_DATABASE }}.ETL;

-- ETL.INBOUND STAGE
CREATE STAGE IF NOT EXISTS {{ SF_DATABASE }}.ETL.INBOUND 
URL='{{ SF_S3_ETLDATA_URL }}inbound/' 
STORAGE_INTEGRATION={{ SF_STORAGE_INTEGRATION }} 
ENCRYPTION=(TYPE='AWS_SSE_S3') 
DIRECTORY = (ENABLE = TRUE, AUTO_REFRESH=TRUE);

-- ETL.OUTBOUND STAGE
CREATE STAGE IF NOT EXISTS {{ SF_DATABASE }}.ETL.OUTBOUND 
URL='{{ SF_S3_ETLDATA_URL }}outbound/' 
STORAGE_INTEGRATION={{ SF_STORAGE_INTEGRATION }} 
ENCRYPTION=(TYPE='AWS_SSE_S3') 
DIRECTORY = (ENABLE = TRUE, AUTO_REFRESH=TRUE);

