FROM python:3.9

WORKDIR /build

COPY schemachange /build/schemachange
COPY requirements.txt setup.cfg README.md /build/

RUN pip3 install --upgrade build
RUN pip3 install --upgrade -r requirements.txt
RUN python3 -m build


FROM python:3.9

COPY --from=0 /build/dist/schemachange-*-py3-none-any.whl /tmp/
RUN pip3 install /tmp/schemachange-*-py3-none-any.whl && rm /tmp/schemachange-*-py3-none-any.whl

ENTRYPOINT schemachange
