FROM ghcr.io/astral-sh/uv:python3.9-bookworm-slim

WORKDIR /build

COPY schemachange /build/schemachange
COPY pyproject.toml uv.lock README.md LICENSE NOTICE /build/

RUN uv build


FROM python:3.9-slim

COPY --from=0 /build/dist/schemachange-*-py3-none-any.whl /tmp/
RUN pip3 install /tmp/schemachange-*-py3-none-any.whl && rm /tmp/schemachange-*-py3-none-any.whl

ENTRYPOINT ["schemachange"]
