USE SCHEMA {{ SF_DATABASE }}.ETL;


CREATE OR REPLACE FUNCTION COPYSELECT("TABLESCHEMA_P" VARCHAR(16777216), "TABLENAME_P" VARCHAR(16777216), "METADATACNT_P" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
AS ' SELECT listagg(concat( '' $'' , to_char(ROW_NUM)), '', '') within group(Order by ROW_NUM) FROM ( select ROW_NUMBER() OVER(ORDER BY ORDINAL_POSITION) as ROW_NUM, COLUMN_NAME, ORDINAL_POSITION FROM INFORMATION_SCHEMA.COLUMNS WHERE 1=1 AND TABLE_SCHEMA = upper("TABLESCHEMA_P") AND TABLE_NAME = upper("TABLENAME_P") qualify row_num <= ((SELECT COUNT(*) From INFORMATION_SCHEMA.COLUMNS where 1=1 AND TABLE_SCHEMA = upper("TABLESCHEMA_P") AND TABLE_NAME = upper("TABLENAME_P") ) - "METADATACNT_P") ) X ';
