USE SCHEMA {{ SF_DATABASE }}.ETL;


CREATE OR REPLACE VIEW GETALLSCHEMAOBJECTS_VW(
	SCHEMA_NAME,
	EXTERNAL_TABLES,
	FILE_FORMAT,
	FUNCTIONS,
	PIPES,
	STORED_PROCS,
	SEQ,
	STAGES,
	TABLES,
	VIEWS
) as SELECT S.SCHEMA_NAME
        , COUNT(DISTINCT ET.TABLE_NAME) AS EXTERNAL_TABLES
        , COUNT(DISTINCT FF.FILE_FORMAT_NAME) AS FILE_FORMAT
        , COUNT(DISTINCT FU.FUNCTION_NAME) AS FUNCTIONS
        , COUNT(DISTINCT P.PIPE_NAME)  AS PIPES
        , COUNT(DISTINCT SP.PROCEDURE_NAME) AS STORED_PROCS
        , COUNT(DISTINCT SEQ.SEQUENCE_NAME) AS SEQ
        , COUNT(DISTINCT STG.STAGE_NAME) AS STAGES
        , COUNT(DISTINCT T.TABLE_NAME) AS TABLES 
        , COUNT(DISTINCT V.TABLE_NAME) AS VIEWS
--, SUM(COUNT(ET.*), COUNT(FF.*), COUNT(FU.*), COUNT(P.*), COUNT(SP.*), COUNT(SEQ.*), COUNT(STG.*), COUNT(T.*),COUNT(V.*))
FROM INFORMATION_SCHEMA.SCHEMATA S 
LEFT JOIN INFORMATION_SCHEMA.EXTERNAL_TABLES ET ON ET.TABLE_SCHEMA = S.SCHEMA_NAME
LEFT JOIN INFORMATION_SCHEMA.FILE_FORMATS FF ON FF.FILE_FORMAT_SCHEMA = S.SCHEMA_NAME
LEFT JOIN INFORMATION_SCHEMA.FUNCTIONS FU ON FU.FUNCTION_SCHEMA = S.SCHEMA_NAME
LEFT JOIN INFORMATION_SCHEMA.PIPES P ON P.PIPE_SCHEMA = S.SCHEMA_NAME
LEFT JOIN INFORMATION_SCHEMA.PROCEDURES SP ON SP.PROCEDURE_SCHEMA = S.SCHEMA_NAME
LEFT JOIN INFORMATION_SCHEMA.SEQUENCES SEQ ON SEQ.SEQUENCE_SCHEMA = S.SCHEMA_NAME
LEFT JOIN INFORMATION_SCHEMA.STAGES STG ON STG.STAGE_SCHEMA = S.SCHEMA_NAME
LEFT JOIN INFORMATION_SCHEMA.TABLES T ON T.TABLE_SCHEMA = S.SCHEMA_NAME AND T.TABLE_TYPE = 'BASE TABLE'
LEFT JOIN INFORMATION_SCHEMA.VIEWS V ON V.TABLE_SCHEMA = S.SCHEMA_NAME
WHERE S.SCHEMA_NAME <> 'INFORMATION_SCHEMA'
GROUP BY S.SCHEMA_NAME
ORDER BY 1;


CREATE OR REPLACE VIEW GETCOLUMN_VW(
	TABLE_SCHEMA,
	TABLE_NAME,
	COLUMN_NAME,
	DATA_TYPE,
	IS_NULLABLE,
	TABLE_TYPE
) as SELECT 
     C.TABLE_SCHEMA
    , C.TABLE_NAME
    , C.COLUMN_NAME
    , C.DATA_TYPE
    , C.IS_NULLABLE
    , T.TABLE_TYPE
FROM INFORMATION_SCHEMA.COLUMNS C
LEFT JOIN INFORMATION_SCHEMA.TABLES T on T.TABLE_NAME = C.TABLE_NAME
WHERE 1=1
ORDER BY C.COLUMN_NAME,C.TABLE_NAME;
